name: Generate README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Gerar README.md
        run: node generate-readme.js

      - name: Fazer commit das alterações
        if: matrix.os == 'ubuntu-latest'  # Faz commit apenas no Ubuntu para evitar conflitos
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Atualizar README.md automaticamente' || echo "Sem mudanças para commitar"
          git push
