yaml
name: Generate README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ ubuntu-latest }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Generate README.md
        run: node generate-readme.js  

      - name: Check if README.md was created or updated
        id: check_changes
        run: |
          if git ls-files --error-unmatch README.md > /dev/null 2>&1; then
            if git diff --quiet README.md; then
              echo "changed=false" >> $GITHUB_ENV
            else
              echo "changed=true" >> $GITHUB_ENV
            fi
          else
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit updates
        if: env.changed == 'true'
        run: |
          git config --global user.name 'taykazuhiro'
          git config --global user.email 'taykazuhiro@gmail.com'
          git add README.md
          git commit -m 'Create/Update README.md automatically'
          git push
